### ISSUE TITLE
Laravel 9 released

### ISSUE THREAD

**Issue by rahwinia51** [georgeboot/laravel-echo-api-gateway#18]
Please add laravel 9 version in requirements.

**Comment by saboreo** [comment]
Need Laravel 9 support.

**Comment by saboreo** [comment]
Please could you add a Laravel 9 support?

**Comment by jdavidbakr** [comment]
Any chance this is going to happen?

**Comment by georgeboot** [comment]
Can you add a pull request for this?

**Comment by jdavidbakr** [comment]
PR submitted.
