### ISSUE TITLE
Remove AXIOS dependency

### ISSUE THREAD

**Issue by Adesin-fr** [georgeboot/laravel-echo-api-gateway#30]
We should replace Axios by browser's fetch API, which is now a few years old and should be supported on most users' browsers.

It's a few lines change, I'll handle it ASAP.

**Comment by Adesin-fr** [comment]
WelL...
In facts, building doesn't work anymore if axios is not present, since laravel's echo js package needs it...

**Comment by leob** [comment]
@Adesin-fr Okay so we're not going ahead with this one ... yeah it's fine, it works with Axios (our own app already uses Axios anyway so for us it doesn't add to the bundle size)

**Comment by Adesin-fr** [comment]
That what not exactly the case : my app did not use axios, I removed it from my package.json... But NodeJS because of others packages (such as Echo), it's still used ;)

**Comment by leob** [comment]
> That what not exactly the case : my app did not use axios, I removed it from my package.json... But NodeJS because of others packages (such as Echo), it's still used ;)

@Adesin-fr Yes I understand, but our app does use Axios ;-)

(and Echo yes that's pretty essential within the architecture, Laravel depends on ir)
